Repository sgfdevs/h4g-api-jobs, pull requests merged in 2020-11, with the labels that each got.

#8 Update composer to require PHP7.3
  composer.json
  composer.lock
Labels: dependencies

#1 Add README.md for contributing to the project.
  README-Laravel.md
  README.md
Labels: documentation

#9 Update sass-loader
  package-lock.json
  package.json
Labels: bug, dependencies
